### ISSUE TITLE
Can you turn off egress or make it optional under networkpolicy

### ISSUE THREAD

**Issue by disser4** [yasn77/pgbouncer#1]
https://github.com/yasn77/pgbouncer/blob/master/helm/pgbouncer/templates/networkpolicy.yaml
This is causing anyone that is trying to use /etc/resolve.conf issues in their pods

**Comment by yasn77** [comment]
@disser4 Thanks for opening the first issue 🎉 

I've made NetworkPolicy config a bit more flexible in #2 

I'll cut a new release. Hope it's all fine

**Comment by disser4** [comment]
Thank you!
